# Generated by Django 4.2.16 on 2024-11-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
