# Generated by Django 4.2.16 on 2024-11-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_product_quantidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantidade',
            new_name='amount',
        ),
    ]
